### ISSUE TITLE
"self update" gives unexpected output

### ISSUE THREAD

**Issue by celtic-coder** [vensko/pint#4]
Running the "self update" gives the following output:

`C:\pint>pint self-update`
`Fetching https://raw.githubusercontent.com/vensko/pint/master/pint.cmd`
`Pint was updated to the latest version.`
`" || exit /b 1 was unexpected at this time.`

![pint-self-update](https://user-images.githubusercontent.com/11787866/34996280-0a14697c-fad1-11e7-9676-7c0c8588f166.png)

This looks to be coming from line 27 of the script:

`%POWERSHELL% -NoLogo -NoProfile -executionpolicy bypass "$s = ${%PINT%} | out-string; $s += """pint-start %_args%"""; iex($s)" || exit /b 1`

**Comment by celtic-coder** [comment]
PowerShell is running on Windows 7 64-bit.

`C:\pint>powershell`
`Windows PowerShell`
`Copyright (C) 2012 Microsoft Corporation. All rights reserved.`

`PS C:\pint> $PSVersionTable.PSVersion`

`Major  Minor  Build  Revision`
`-----  -----  -----  --------`
`3      0      -1     -1`

**Comment by vensko** [comment]
Does this reoccur after manual update (download and replace the file)?

**Comment by celtic-coder** [comment]
Hi Dzmitry,

When I manually downloaded the latest version of "pint.cmd" and then ran the "self-update" command it works without any issue:

![pint-self-update-new](https://user-images.githubusercontent.com/11787866/35100731-c48ba566-fc54-11e7-8d71-a3bff928a2dd.png)

Thanks!
Liam.
